package com.agenticai.interviewrepo.service;

import com.agenticai.interviewrepo.dto.*;
import com.agenticai.interviewrepo.model.*;
import com.agenticai.interviewrepo.repository.*;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import jakarta.transaction.Transactional;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.web.server.ResponseStatusException;

import java.time.LocalDate;
import java.util.*;

/**
 * Study plans belong to a student. Plans are generated by the AI service's Preparation Agent (Team B),
 * stored here with the full AI response, and each priority topic becomes a Progress item.
 */
@Service
public class StudyPlanService {

    private static final Logger log = LoggerFactory.getLogger(StudyPlanService.class);
    public static final String NOT_STARTED = "Not Started";
    public static final String IN_PROGRESS = "In Progress";
    public static final String COMPLETED = "Completed";

    private final StudyPlanRepository plans;
    private final ProgressRepository progress;
    private final StudentRepository students;
    private final CompanyRepository companies;
    private final CurrentUserService currentUser;
    private final AiServiceClient ai;
    private final ObjectMapper objectMapper;

    public StudyPlanService(StudyPlanRepository plans, ProgressRepository progress, StudentRepository students,
                            CompanyRepository companies, CurrentUserService currentUser, AiServiceClient ai,
                            ObjectMapper objectMapper) {
        this.plans = plans; this.progress = progress; this.students = students; this.companies = companies;
        this.currentUser = currentUser; this.ai = ai; this.objectMapper = objectMapper;
    }

    /** Calls the AI service, then stores the plan and one progress item per priority topic. */
    @Transactional
    public StudyPlanResponse generate(StudyPlanGenerateRequest request) {
        Student student = currentStudent();
        int days = request.getDaysAvailable() != null ? request.getDaysAvailable() : 14;
        String company = request.getCompany().trim();
        String role = blankToNull(request.getRole());

        Map<String, Object> aiRequest = new LinkedHashMap<>();
        aiRequest.put("company", company);
        if (role != null) aiRequest.put("role", role);
        aiRequest.put("days_available", days);
        if (blankToNull(request.getMessage()) != null) aiRequest.put("message", request.getMessage().trim());
        Map<String, Object> aiPlan = ai.preparation(aiRequest); // 503/400 on failure; nothing is stored

        StudyPlan plan = new StudyPlan();
        plan.setStudent(student);
        plan.setTitle(truncate(company + (role != null ? " " + role : "") + " preparation plan", 100));
        plan.setDescription(asString(aiPlan.get("summary")));
        plan.setTargetCompanyName(truncate(company, 150));
        companies.findByNameIgnoreCase(company).ifPresent(plan::setTargetCompany);
        plan.setTargetRole(role != null ? truncate(role, 100) : null);
        plan.setDaysAvailable(days);
        plan.setStartDate(LocalDate.now());
        plan.setTargetDate(LocalDate.now().plusDays(days));
        plan.setStatus(NOT_STARTED);
        plan.setSource("AI");
        plan.setPlanJson(toJson(aiPlan));
        plan = plans.save(plan);

        List<Progress> items = new ArrayList<>();
        for (TopicSeed seed : topicSeeds(aiPlan)) {
            Progress item = new Progress();
            item.setStudyPlan(plan);
            item.setTopic(truncate(seed.topic(), 100));
            item.setCategory(seed.category() != null ? truncate(seed.category(), 50) : null);
            item.setPriority(seed.priority());
            item.setSampleQuestions(seed.samples().isEmpty() ? null : String.join("\n", seed.samples()));
            item.setStatus(NOT_STARTED);
            items.add(item);
        }
        progress.saveAll(items);
        log.info("Stored AI study plan {} with {} topics for student {}", plan.getId(), items.size(), student.getId());
        return toResponse(plan, items);
    }

    @Transactional
    public List<StudyPlanResponse> listMine() {
        Student student = currentStudent();
        return plans.findByStudent_IdOrderByCreatedAtDesc(student.getId()).stream()
                .map(plan -> toResponse(plan, progress.findByStudyPlan_IdOrderByPriorityAscCreatedAtAsc(plan.getId())))
                .toList();
    }

    @Transactional
    public StudyPlanResponse get(UUID id) {
        StudyPlan plan = findReadable(id);
        return toResponse(plan, progress.findByStudyPlan_IdOrderByPriorityAscCreatedAtAsc(id));
    }

    @Transactional
    public StudyPlanResponse update(UUID id, StudyPlanUpdateRequest request) {
        StudyPlan plan = findOwned(id);
        if (blankToNull(request.getTitle()) != null) plan.setTitle(request.getTitle().trim());
        if (request.getDescription() != null) plan.setDescription(request.getDescription());
        if (request.getTargetDate() != null) plan.setTargetDate(request.getTargetDate());
        return toResponse(plans.save(plan), progress.findByStudyPlan_IdOrderByPriorityAscCreatedAtAsc(id));
    }

    @Transactional
    public void delete(UUID id) {
        StudyPlan plan = findOwned(id);
        progress.deleteByStudyPlan_Id(plan.getId());
        plans.delete(plan);
    }

    // ---------- shared with ProgressService ----------

    /**
     * The current user's Student profile; 403 if the caller is not a student. Self-registered students
     * (created via /api/auth/sync) have no profile row yet, so one is created on first use.
     */
    public Student currentStudent() {
        User user = currentUser.getCurrentUser();
        return students.findByLogin(user).orElseGet(() -> {
            if (user.getRole() != Role.STUDENT)
                throw new ResponseStatusException(HttpStatus.FORBIDDEN, "Only students have study plans");
            Student student = new Student();
            student.setLogin(user);
            String name = user.getName() != null && !user.getName().isBlank() ? user.getName()
                    : user.getEmail() != null ? user.getEmail().split("@")[0] : "Student";
            student.setName(truncate(name, 100));
            log.info("Creating missing student profile for user {}", user.getId());
            return students.save(student);
        });
    }

    /** A plan owned by the current student (404 if missing or owned by someone else). */
    public StudyPlan findOwned(UUID id) {
        Student student = currentStudent();
        StudyPlan plan = plans.findById(id).orElseThrow(() -> notFound("Study plan not found"));
        if (!plan.getStudent().getId().equals(student.getId())) throw notFound("Study plan not found");
        return plan;
    }

    /** Owner or admin may read. */
    public StudyPlan findReadable(UUID id) {
        StudyPlan plan = plans.findById(id).orElseThrow(() -> notFound("Study plan not found"));
        User user = currentUser.getCurrentUser();
        if (user.getRole() == Role.ADMIN) return plan;
        if (!plan.getStudent().getLogin().getId().equals(user.getId())) throw notFound("Study plan not found");
        return plan;
    }

    /** Derives the plan status from its progress items. */
    public void refreshStatus(StudyPlan plan) {
        List<Progress> items = progress.findByStudyPlan_IdOrderByPriorityAscCreatedAtAsc(plan.getId());
        String status;
        if (!items.isEmpty() && items.stream().allMatch(p -> COMPLETED.equals(p.getStatus()))) status = COMPLETED;
        else if (items.stream().anyMatch(p -> !NOT_STARTED.equals(p.getStatus()))) status = IN_PROGRESS;
        else status = NOT_STARTED;
        if (!status.equals(plan.getStatus())) {
            plan.setStatus(status);
            plans.save(plan);
        }
    }

    public StudyPlanResponse toResponse(StudyPlan plan, List<Progress> items) {
        int completed = (int) items.stream().filter(p -> COMPLETED.equals(p.getStatus())).count();
        int percent = items.isEmpty() ? 0 : Math.round(completed * 100f / items.size());
        return new StudyPlanResponse(plan.getId(), plan.getStudent().getId(), plan.getTitle(), plan.getDescription(),
                plan.getTargetCompany() != null ? plan.getTargetCompany().getId() : null,
                plan.getTargetCompanyName() != null ? plan.getTargetCompanyName()
                        : plan.getTargetCompany() != null ? plan.getTargetCompany().getName() : null,
                plan.getTargetRole(), plan.getDaysAvailable(), plan.getStartDate(), plan.getTargetDate(),
                plan.getStatus(), plan.getSource(), items.size(), completed, percent, fromJson(plan.getPlanJson()),
                items.stream().map(ProgressResponse::from).toList(), plan.getCreatedAt(), plan.getUpdatedAt());
    }

    // ---------- AI plan parsing ----------

    record TopicSeed(String topic, String category, Integer priority, List<String> samples) {}

    /** priority_topics from the AI plan; falls back to the rounds' key_topics when absent. */
    static List<TopicSeed> topicSeeds(Map<String, Object> aiPlan) {
        List<TopicSeed> seeds = new ArrayList<>();
        Set<String> seen = new HashSet<>();
        if (aiPlan.get("priority_topics") instanceof List<?> topics) {
            for (Object o : topics) {
                if (!(o instanceof Map<?, ?> t) || blankToNull(asString(t.get("topic"))) == null) continue;
                String topic = asString(t.get("topic")).trim();
                if (!seen.add(topic.toLowerCase())) continue;
                Integer priority = t.get("priority") instanceof Number n ? n.intValue() : null;
                seeds.add(new TopicSeed(topic, asString(t.get("category")), priority, strings(t.get("sample_questions"))));
            }
        }
        if (seeds.isEmpty() && aiPlan.get("rounds") instanceof List<?> rounds) {
            int priority = 1;
            for (Object o : rounds) {
                if (!(o instanceof Map<?, ?> r)) continue;
                for (String topic : strings(r.get("key_topics"))) {
                    if (seen.add(topic.toLowerCase()))
                        seeds.add(new TopicSeed(topic, asString(r.get("round_type")), priority++, List.of()));
                }
            }
        }
        return seeds;
    }

    private static List<String> strings(Object value) {
        if (!(value instanceof List<?> list)) return List.of();
        return list.stream().filter(Objects::nonNull).map(Object::toString).map(String::trim)
                .filter(s -> !s.isEmpty()).toList();
    }

    private String toJson(Map<String, Object> value) {
        try {
            return objectMapper.writeValueAsString(value);
        } catch (Exception e) {
            throw new ResponseStatusException(HttpStatus.INTERNAL_SERVER_ERROR, "Could not store AI plan");
        }
    }

    private Map<String, Object> fromJson(String json) {
        if (json == null || json.isBlank()) return Map.of();
        try {
            return objectMapper.readValue(json, new TypeReference<Map<String, Object>>() {});
        } catch (Exception e) {
            log.warn("Unreadable plan_json: {}", e.getMessage());
            return Map.of();
        }
    }

    private static String asString(Object value) { return value == null ? null : value.toString(); }

    private static String blankToNull(String value) { return value == null || value.isBlank() ? null : value.trim(); }

    private static String truncate(String value, int max) { return value.length() <= max ? value : value.substring(0, max); }

    private static ResponseStatusException notFound(String message) {
        return new ResponseStatusException(HttpStatus.NOT_FOUND, message);
    }
}
